# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Test and Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Deployment Environment
        options:
          - dev
          - prod
        message:
          required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    name: Build and Deploy workflows to the target environment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Zulu JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build and Test
        run: |          
          ./gradlew clean build
      - name: Deploy
        run: |
          cd src          
          echo "Deploying tasks"
          ./deploy_tasks.sh
          echo "Deploying workflows"
          ./deploy_workflows.sh
    env:
      CONDUCTOR_SERVER_URL: ${{ secrets.CONDUCTOR_SERVER_URL }}
      CONDUCTOR_AUTH_KEY: ${{ secrets.CONDUCTOR_AUTH_KEY }}
      CONDUCTOR_AUTH_SECRET: ${{ secrets.CONDUCTOR_AUTH_SECRET }}
